- name: Install Android Command Line Tools
  run: |
    mkdir -p $HOME/android-sdk/cmdline-tools
    cd $HOME/android-sdk/cmdline-tools
    curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
    unzip -q commandlinetools.zip
    mv cmdline-tools latest   # ✅ ضعها في مجلد "latest"
    export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
    yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "build-tools;33.0.2" "platforms;android-33"